---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluwhale
description: This is a personal Fedora Atomic build. 

# base-image: quay.io/fedora-ostree-desktops/silverblue
base-image: ghcr.io/ublue-os/silverblue-main # to use with xone
image-version: 43 

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - from-file: modules/terra.yml
  # Packages
  - from-file: packages/system.yml
  - from-file: packages/gaming.yml
  - from-file: packages/dev.yml
  - from-file: packages/flatpaks.yml
  - from-file: packages/flatpaks-gnome.yml
  # From COPR
  - from-file: packages/copr-topgrade.yml
  - from-file: packages/copr-cachyos.yml
  - from-file: packages/copr-xariann-tools.yml
  # Extra modules
  - from-file: modules/gnome-extensions.yml
  - from-file: modules/brew.yml
  - from-file: modules/shell.yml
  - from-file: modules/akmods.yml

  - type: systemd
    system:
      enabled:
        - podman.socket
        - greenboot-healthcheck.service 
  
  - type: initramfs

  - type: signing
