---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluwhale
description: This is a personal Fedora Atomic build. 

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 43 

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - from-file: terra.yml
  - from-file: packages-system.yml
  - from-file: packages-gaming.yml
  - from-file: flatpaks.yml

  #- type: akmods
  #  base: main
  #  install:
  #    - xone

  - type: chezmoi
    repository: "https://gitlab.com/Xariann/dotfiles" # my dotfiles repo
    all-users: false # make users have to enable chezmoi manually
    file-conflict-policy: replace # override changed files with those from the repo

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
  
  - type: script
    scripts:
      - firmware.sh 
      - zsh.sh

  - type: systemd
    system:
      enabled:
        - podman.socket
        - greenboot-healthcheck.service 
  
  - type: initramfs

  - type: signing
