---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluwhale
description: This is a test image

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 

modules:
  - type: files
    files:
      - source: system
        destination: /
        
  - type: script
    scripts:
      - enable-terra-mesa.sh

  - from-file: packages-system.yml
  - from-file: packages-gaming.yml
  - from-file: flatpaks.yml

  - type: akmods
    base: main
    install:
      - xone

  - type: systemd
    system:
      enabled:
        - podman.socket
        - greenboot-healthcheck.service 

  - type: script
    scripts:
      - firmware.sh 
      #- zsh.sh

  - type: signing
