---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluweird
description: This is a test image

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 

modules:

  - type: files
    files:
      - source: system
        destination: /
      
  - type: dnf
    repos:
      copr:
        - faugus/faugus-launcher
        - bieszczaders/kernel-cachyos-addons
        - lilay/topgrade
        - solopasha/hyprland
        - avengemedia/dms
    install:
      packages:
        - goverlay
        - steam
        - input-remapper
        - mangohud
        - vkBasalt
        - just
        - protontricks
        - greenboot
        - greenboot-default-health-checks
        - ghostty
        # COPR: faugus-launcher
        - faugus-launcher
        # COPR: bieszczaders/kernel-cachyos-addons
        - scx-scheds
        - scx-tools
        - scx-manager
        # COPR: lilay/topgrade
        - topgrade
        # COPR solopasha/hyprland
        - hyprland
        - xdg-desktop-portal-hyprland
        # COPR avengemedia/dms
        - dms
        - dms-greeter
        
  
  - type: akmods
    base: main
    install:
        - xone

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.discordapp.Discord
          - com.obsproject.Studio
          - io.github.plrigaux.sysd-manager
          - io.podman_desktop.PodmanDesktop
          - org.kde.krita
          - it.mijorus.gearlever
          - org.onlyoffice.desktopeditors
          - io.github.ungoogled_software.ungoogled_chromium
          - org.gnome.World.PikaBackup
          - com.github.tchx84.Flatseal
          - com.ranfdev.DistroShelf
          - io.github.flattool.Warehouse
          - net.davidotek.pupgui2
          - org.localsend.localsend_app
          - io.github.radiolamp.mangojuice
          - org.kde.isoimagewriter
          - io.github.tobagin.keysmith
          - be.alexandervanhee.gradia
          - com.visualstudio.code
          - page.tesk.Refine
      - scope: user
      
  - type: systemd
    system:
      enabled:
        - podman.socket
        #- greenboot-healthcheck.service

  - type: script
    scripts:
      - firmware.sh
        
  - type: signing
