---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluwhale
description: This is a personal Fedora Atomic build. 

# base-image: quay.io/fedora-ostree-desktops/silverblue
base-image: ghcr.io/ublue-os/silverblue-main # to use with xone
image-version: 43 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - from-file: modules/terra.yml      
        
  - type: dnf
    repos:
      copr:
        - xariann/tools
        - lilay/topgrade
        - bieszczaders/kernel-cachyos-addons
    install:
      packages:
        # System
        - fastfetch
        - fresh # Terra
        - gh
        - greenboot
        - greenboot-default-health-checks
        - jetbrains-mono-fonts-all
        - rsync
        # Gaming 
        - steam
        - goverlay
        - mangohud
        - vkBasalt
        # Dev
        - distrobox
        - yadm
        # COPR: xariann-tools
        - nautilus-copy-path
        - boot-windows
        # COPR: lilay/topgrade
        - topgrade
        # COPR: bieszczaders/kernel-cachyos-addons
        - scx-scheds
        - scx-tools
        - scx-manager
  # Extra modules
  - from-file: modules/gnome-extensions.yml
  - from-file: modules/brew.yml
  - from-file: modules/shell.yml
  - from-file: modules/justfiles.yml
  - from-file: modules/akmods.yml

  - type: systemd
    system:
      enabled:
        - podman.socket
        - greenboot-healthcheck.service 
  
  - type: initramfs

  - type: signing

  - type: os-release
    properties:
      ID: bluwhale
      ID_LIKE: fedora
      NAME: Bluwhale
      PRETTY_NAME: Bluwhale
