flatpak = [
  { package = "com.discordapp.Discord", options = { systemwide = true } },
  { package = "com.obsproject.Studio", options = { systemwide = true } },
  { package = "io.github.plrigaux.sysd-manager", options = { systemwide = true } },
  { package = "io.podman_desktop.PodmanDesktop", options = { systemwide = true } },
  { package = "org.kde.krita", options = { systemwide = true } },
  { package = "it.mijorus.gearlever", options = { systemwide = true } },
  { package = "org.onlyoffice.desktopeditors", options = { systemwide = true } },
  { package = "io.github.ungoogled_software.ungoogled_chromium", options = { systemwide = true } },
  { package = "org.gnome.World.PikaBackup", options = { systemwide = true } },
  { package = "com.github.tchx84.Flatseal", options = { systemwide = true } },
  { package = "com.ranfdev.DistroShelf", options = { systemwide = true } },
  { package = "io.github.flattool.Warehouse", options = { systemwide = true } },
  { package = "net.davidotek.pupgui2", options = { systemwide = true } },
  { package = "org.kde.elisa", options = { systemwide = true } },
  { package = "org.kde.gwenview", options = { systemwide = true } },
  { package = "org.kde.kcalc", options = { systemwide = true } },
  { package = "org.kde.kmahjongg", options = { systemwide = true } },
  { package = "org.kde.kmines", options = { systemwide = true } },
  { package = "org.kde.kolourpaint", options = { systemwide = true } },
  { package = "org.kde.krdc", options = { systemwide = true } },
  { package = "org.kde.skanpage", options = { systemwide = true } },
  { package = "org.localsend.localsend_app", options = { systemwide = true } },
  { package = "io.github.radiolamp.mangojuice", options = { systemwide = true } },
]
