# /usr/share/bluwhale/just/Justfile
# System-wide just recipes for post-install setup

# Sync dotfiles
[group('Post-Install Setup')]
sync-dots:
    just --justfile /usr/share/bluwhale/just/20-sync-dots.just sync-dots
    
# Secure Boot enrollment - uses universalblue public key
[group('Gaming')]
enroll-secure-boot:
    just --justfile /usr/share/bluwhale/just/50-secure-boot.just enroll-secure-boot

# Fish shell
[group('Post-Install Setup')]
set-fish-shell:
    just --justfile /usr/share/bluwhale/just/40-shell-fish.just set-fish-shell
