# /usr/share/bluwhale/just/Justfile
# System-wide just recipes for post-install setup

# Install homebrew
[group('Post-Install Setup')]
setup-brew:
    just --justfile /usr/share/bluwhale/just/10-homebrew.just setup-brew

# Sync Dank Material Shell dotfiles
[group('Post-Install Setup')]
sync-dots:
    just --justfile /usr/share/bluwhale/just/20-sync-dots.just sync-dots
    
# Secure Boot enrollment - uses universalblue public key
[group('Gaming')]
enroll-secure-boot:
    just --justfile /usr/share/bluwhale/just/50-secure-boot.just enroll-secure-boot
