# ./Arch-Config/metapac/groups/default.toml

arch = [
  "ansible",
  "arch-update",
  "bat",
  "bridge-utils",
  "btrfs-assistant-git",
  "cosign",
  "curl",
  "dracut",
  "duperemove",
  "eza",
  "figlet",
  "fish",
  "fwupd",
  "grsync",
  "grub-btrfs",
  "gwenview",
  "gnome-boxes",
  "haruna",
  "inotify-tools",
  "iptables-nft",
  "kdeconnect",
  "kdegraphics-thumbnailers",
  "kdenlive",
  "kwalletmanager",
  "kwin-scripts-dynamic-workspaces",
  "kvantum",
  "less",
  "libva-utils", # gpu info tools
  "okular",
  "partitionmanager",
  "plasma6-applets-arch-update-notifier",
  "podman",
  "power-profiles-daemon",
  "qt5-tools", 
  "rsync",
  "sbsigntools",
  "snap-pac", # snapper support for pacman
  "starship",
  "sysd-manager",
  "tree",
  "unarchiver",
  "unrar",
  "usbutils",
  "visual-studio-code-bin",
  "wireless-regdb",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-user-dirs",
  "ydotool",
  "zenity",
  "zip",
  ]
