arch = [
 "7zip",
 "cachyos-kernel-manager",
 "cachyos-keyring",
 "cachyos-mirrorlist",
 "cachyos-v3-mirrorlist",
 "cachyos-v4-mirrorlist",
 "mesa-git",
 "paru",
 "plasma-applet-window-buttons",
 "plasma-browser-integration",
]
