arch = [
 "arch-update",
 "balena-etcher",
 "bpftune-git",
 "chaotic-keyring",
 "chaotic-mirrorlist",
 "downgrade",
 "dxvk-mingw-git",
 "kf6-servicemenus-rootactions",
 "kwin-effect-rounded-corners-git",
 "kwin-effects-forceblur",
 "libinput-gestures",
 "libinput-gestures-qt",
 "linux-cachyos",
 "linux-cachyos-headers",
 "noto-color-emoji-fontconfig",
 "os-prober-btrfs",
 "pace",
 "pamac",
 "plasma6-applets-window-title",
 "plasma6-wallpapers-blurredwallpaper",
 "snapper-support",
 "snapper-tools",
 "ttf-jetbrains-mono-nerd",
 "ttf-nerd-fonts-symbols-mono",
 "update-grub",
 "zenergy-dkms-git",
]
