set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    source /usr/lib/ujust/libformatting.sh
    echo "$(Urllink "https://docs.projectbluefin.io/administration#community-aliases-and-workarounds" "Click here to view the Universal Blue just documentation")"
    /usr/bin/ujust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "/usr/share/ublue-os/just/00-default.just"
import "/usr/share/ublue-os/just/10-update.just"
import "/usr/share/ublue-os/just/15-luks.just"
import "/usr/share/ublue-os/just/20-clean.just"
import "/usr/share/ublue-os/just/30-distrobox.just"
import "/usr/share/ublue-os/just/31-toolbox.just"
import "/usr/share/ublue-os/just/40-nvidia.just"
import "/usr/share/ublue-os/just/50-akmods.just"
import? "/usr/share/ublue-os/just/60-custom.just"
import "/usr/share/ublue-os/just/80-bazzite.just"
import "/usr/share/ublue-os/just/81-bazzite-fixes.just"
import "/usr/share/ublue-os/just/82-bazzite-apps.just"
import "/usr/share/ublue-os/just/82-bazzite-cdemu.just"
import "/usr/share/ublue-os/just/82-bazzite-sunshine.just"
import "/usr/share/ublue-os/just/82-bazzite-rmlint.just"
import "/usr/share/ublue-os/just/82-bazzite-waydroid.just"
import "/usr/share/ublue-os/just/83-my-apps.just"
import "/usr/share/ublue-os/just/83-bazzite-audio.just"
import "/usr/share/ublue-os/just/84-bazzite-virt.just"
import "/usr/share/ublue-os/just/85-bazzite-image.just"
import "/usr/share/ublue-os/just/86-bazzite-windows.just"
import "/usr/share/ublue-os/just/87-bazzite-framegen.just"
import "/usr/share/ublue-os/just/88-bazzite-webapps.just"
import "/usr/share/ublue-os/just/89-bazzite-mesa-git.just"
import "/usr/share/ublue-os/just/90-bazzite-picker.just"
import "/usr/share/ublue-os/just/90-bazzite-de.just"
